import { redirect } from "next/navigation";
import { getSession } from "@/lib/session";
import Loader from "@/components/common/loader";
import { Suspense } from "react";

export const metadata = {
  title: "X-Pense",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getSession();

  // Redirect to dashboard if the user is authenticated and not new
  if (session?.userId && !session?.isNewUser) {
    redirect("/dashboard");
  }

  return (
    <section className="w-full max-w-screen-sm mx-auto bg-white flex flex-col h-dvh">
      <Suspense fallback={<Loader />}>
        <div className="flex-grow overflow-y-auto">{children}</div>
      </Suspense>
    </section>
  );
}
