import localFont from "next/font/local";
import "../globals.css";
import { redirect } from "next/navigation";
import { getSession } from "@/lib/session";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "X-Pense",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getSession();

  if (session) {
    redirect("/dashboard");
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="w-full max-w-screen-sm mx-auto bg-slate-50">{children}</main>
      </body>
    </html>
  );
}
