import localFont from "next/font/local";
import "../globals.css";
import { redirect } from "next/navigation";
import { verifySession } from "@/lib/session";
import NavBar from "@/components/common/navBar";
import NavBarBottom from "@/components/common/navBottom";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "X-Pense",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { isAuth } = await verifySession();
  if (!isAuth) {
    redirect("/auth/login");
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="w-full max-w-screen-sm mx-auto bg-white flex flex-col h-dvh">
          <div className="flex-grow overflow-y-auto">{children}</div>
          <NavBarBottom />
        </main>
      </body>
    </html>
  );
}
