import { redirect } from "next/navigation";
import { verifySession } from "@/lib/session";
import NavBarBottom from "@/components/common/navBottom";
import Loader from "@/components/common/loader";
import { Suspense } from "react";

export const metadata = {
  title: "X-Pense",
  description: "Generated by create next app",
};

// Server Component
export default async function RootLayout({ children }) {
  const sessionPromise = verifySession();

  // Wrap the layout in Suspense with a loading fallback
  return (
    <section className="w-full max-w-screen-sm mx-auto bg-white flex flex-col h-dvh">
      <Suspense fallback={<Loader />}>
        <AuthenticatedContent sessionPromise={sessionPromise}>{children}</AuthenticatedContent>
      </Suspense>
      <NavBarBottom />
    </section>
  );
}

// Server-Side Authenticated Content Wrapper
async function AuthenticatedContent({ sessionPromise, children }) {
  const { isAuth } = await sessionPromise;

  if (!isAuth) {
    redirect("/auth/login");
  }

  return <div className="flex-grow overflow-y-auto">{children}</div>;
}
